// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const nordTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff2e3440), color: Color(0xffd8dee9)),
  'subst': TextStyle(color: Color(0xffd8dee9)),
  'selector-tag': TextStyle(color: Color(0xff81a1c1)),
  'selector-id':
      TextStyle(color: Color(0xff8fbcbb), fontWeight: FontWeight.w700),
  'selector-attr': TextStyle(color: Color(0xff8fbcbb)),
  'selector-class': TextStyle(color: Color(0xff8fbcbb)),
  'property': TextStyle(color: Color(0xff88c0d0)),
  'selector-pseudo': TextStyle(color: Color(0xff88c0d0)),
  'addition': TextStyle(backgroundColor: Color.fromRGBO(163, 190, 140, .5)),
  'deletion': TextStyle(backgroundColor: Color.fromRGBO(191, 97, 106, .5)),
  'built_in': TextStyle(color: Color(0xff8fbcbb)),
  'class': TextStyle(color: Color(0xff8fbcbb)),
  'type': TextStyle(color: Color(0xff8fbcbb)),
  'function': TextStyle(color: Color(0xff88c0d0)),
  'function>.hljs-title': TextStyle(color: Color(0xff88c0d0)),
  'title.hljs-function': TextStyle(color: Color(0xff88c0d0)),
  'keyword': TextStyle(color: Color(0xff81a1c1)),
  'literal': TextStyle(color: Color(0xff81a1c1)),
  'symbol': TextStyle(color: Color(0xff81a1c1)),
  'number': TextStyle(color: Color(0xffb48ead)),
  'regexp': TextStyle(color: Color(0xffebcb8b)),
  'string': TextStyle(color: Color(0xffa3be8c)),
  'title': TextStyle(color: Color(0xff8fbcbb)),
  'params': TextStyle(color: Color(0xffd8dee9)),
  'bullet': TextStyle(color: Color(0xff81a1c1)),
  'code': TextStyle(color: Color(0xff8fbcbb)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'formula': TextStyle(color: Color(0xff8fbcbb)),
  'strong': TextStyle(fontWeight: FontWeight.w700),
  'comment': TextStyle(color: Color(0xff4c566a)),
  'quote': TextStyle(color: Color(0xff4c566a)),
  'doctag': TextStyle(color: Color(0xff8fbcbb)),
  'meta': TextStyle(color: Color(0xff5e81ac)),
  'attr': TextStyle(color: Color(0xff8fbcbb)),
  'attribute': TextStyle(color: Color(0xffd8dee9)),
  'name': TextStyle(color: Color(0xff81a1c1)),
  'section': TextStyle(color: Color(0xff88c0d0)),
  'tag': TextStyle(color: Color(0xff81a1c1)),
  'template-variable': TextStyle(color: Color(0xffd8dee9)),
  'variable': TextStyle(color: Color(0xffd8dee9)),
  'template-tag': TextStyle(color: Color(0xff5e81ac)),
  '.language-aspectj>title': TextStyle(color: Color(0xff88c0d0)),
};
