// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const rainbowTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff474949), color: Color(0xffd1d9e1)),
  'comment': TextStyle(color: Color(0xff969896), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff969896), fontStyle: FontStyle.italic),
  'addition': TextStyle(color: Color(0xffcc99cc)),
  'keyword': TextStyle(color: Color(0xffcc99cc)),
  'literal': TextStyle(color: Color(0xffcc99cc)),
  'selector-tag': TextStyle(color: Color(0xffcc99cc)),
  'type': TextStyle(color: Color(0xffcc99cc)),
  'number': TextStyle(color: Color(0xfff99157)),
  'selector-attr': TextStyle(color: Color(0xfff99157)),
  'selector-pseudo': TextStyle(color: Color(0xfff99157)),
  'doctag': TextStyle(color: Color(0xff8abeb7)),
  'regexp': TextStyle(color: Color(0xff8abeb7)),
  'string': TextStyle(color: Color(0xff8abeb7)),
  'built_in': TextStyle(color: Color(0xffb5bd68)),
  'name': TextStyle(color: Color(0xffb5bd68), fontWeight: FontWeight.w700),
  'section': TextStyle(color: Color(0xffb5bd68), fontWeight: FontWeight.w700),
  'title': TextStyle(color: Color(0xffb5bd68)),
  'selector-id': TextStyle(color: Color(0xffffcc66)),
  'template-variable': TextStyle(color: Color(0xffffcc66)),
  'title.class_': TextStyle(color: Color(0xffffcc66)),
  'variable': TextStyle(color: Color(0xffffcc66)),
  'strong': TextStyle(fontWeight: FontWeight.w700),
  'bullet': TextStyle(color: Color(0xfff99157)),
  'link': TextStyle(color: Color(0xfff99157)),
  'meta': TextStyle(color: Color(0xfff99157)),
  'subst': TextStyle(color: Color(0xfff99157)),
  'symbol': TextStyle(color: Color(0xfff99157)),
  'deletion': TextStyle(color: Color(0xffdc322f)),
  'formula': TextStyle(backgroundColor: Color(0xffeee8d5)),
  'attr': TextStyle(color: Color(0xff81a2be)),
  'attribute': TextStyle(color: Color(0xff81a2be)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
};
