// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const srceryTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff1c1b19), color: Color(0xfffce8c3)),
  'literal': TextStyle(color: Color(0xfffce8c3)),
  'quote': TextStyle(color: Color(0xfffce8c3)),
  'subst': TextStyle(color: Color(0xfffce8c3)),
  'symbol': TextStyle(color: Color(0xff68a8e4)),
  'type': TextStyle(color: Color(0xff68a8e4)),
  'deletion': TextStyle(color: Color(0xffef2f27)),
  'keyword': TextStyle(color: Color(0xffef2f27)),
  'attribute': TextStyle(color: Color(0xfffbb829)),
  'function': TextStyle(color: Color(0xfffbb829)),
  'name': TextStyle(color: Color(0xfffbb829)),
  'section': TextStyle(color: Color(0xfffbb829)),
  'selector-attr': TextStyle(color: Color(0xfffbb829)),
  'selector-class': TextStyle(color: Color(0xfffbb829)),
  'selector-id': TextStyle(color: Color(0xfffbb829)),
  'selector-pseudo': TextStyle(color: Color(0xfffbb829)),
  'title': TextStyle(color: Color(0xfffbb829)),
  'class': TextStyle(color: Color(0xff0aaeb3)),
  'code': TextStyle(color: Color(0xff0aaeb3)),
  'property': TextStyle(color: Color(0xff0aaeb3)),
  'template-variable': TextStyle(color: Color(0xff0aaeb3)),
  'variable': TextStyle(color: Color(0xff0aaeb3)),
  'addition': TextStyle(color: Color(0xff98bc37)),
  'bullet': TextStyle(color: Color(0xff98bc37)),
  'regexp': TextStyle(color: Color(0xff98bc37)),
  'string': TextStyle(color: Color(0xff98bc37)),
  'built_in': TextStyle(color: Color(0xffff5c8f)),
  'params': TextStyle(color: Color(0xffff5c8f)),
  'selector-tag': TextStyle(color: Color(0xff2c78bf)),
  'template-tag': TextStyle(color: Color(0xff2c78bf)),
  'comment': TextStyle(color: Color(0xff918175)),
  'link': TextStyle(color: Color(0xff918175)),
  'meta': TextStyle(color: Color(0xff918175)),
  'number': TextStyle(color: Color(0xff918175)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.w700),
};
