// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const tokyoNightDarkTheme = {
  'comment': TextStyle(color: Color(0xff565f89)),
  'meta': TextStyle(color: Color(0xff565f89)),
  'deletion': TextStyle(color: Color(0xfff7768e)),
  'doctag': TextStyle(color: Color(0xfff7768e)),
  'regexp': TextStyle(color: Color(0xfff7768e)),
  'selector-attr': TextStyle(color: Color(0xfff7768e)),
  'selector-class': TextStyle(color: Color(0xfff7768e)),
  'selector-id': TextStyle(color: Color(0xfff7768e)),
  'selector-pseudo': TextStyle(color: Color(0xfff7768e)),
  'tag': TextStyle(color: Color(0xfff7768e)),
  'template-tag': TextStyle(color: Color(0xfff7768e)),
  'variable.language_': TextStyle(color: Color(0xfff7768e)),
  'link': TextStyle(color: Color(0xffff9e64)),
  'literal': TextStyle(color: Color(0xffff9e64)),
  'number': TextStyle(color: Color(0xffff9e64)),
  'params': TextStyle(color: Color(0xffff9e64)),
  'template-variable': TextStyle(color: Color(0xffff9e64)),
  'type': TextStyle(color: Color(0xffff9e64)),
  'variable': TextStyle(color: Color(0xffff9e64)),
  'attribute': TextStyle(color: Color(0xffe0af68)),
  'built_in': TextStyle(color: Color(0xffe0af68)),
  'keyword': TextStyle(color: Color(0xffbb9af7)),
  'property': TextStyle(color: Color(0xff7dcfff)),
  'subst': TextStyle(color: Color(0xff7dcfff)),
  'title': TextStyle(color: Color(0xff7dcfff)),
  'title.class_': TextStyle(color: Color(0xff7dcfff)),
  'title.class_.inherited__': TextStyle(color: Color(0xff7dcfff)),
  'title.function_': TextStyle(color: Color(0xff7dcfff)),
  'selector-tag': TextStyle(color: Color(0xff73daca)),
  'addition': TextStyle(color: Color(0xff9ece6a)),
  'bullet': TextStyle(color: Color(0xff9ece6a)),
  'quote': TextStyle(color: Color(0xff9ece6a)),
  'string': TextStyle(color: Color(0xff9ece6a)),
  'symbol': TextStyle(color: Color(0xff9ece6a)),
  'code': TextStyle(color: Color(0xff7aa2f7)),
  'formula': TextStyle(color: Color(0xff7aa2f7)),
  'section': TextStyle(color: Color(0xff7aa2f7)),
  'attr': TextStyle(color: Color(0xffbb9af7)),
  'char.escape_': TextStyle(color: Color(0xffbb9af7)),
  'name': TextStyle(color: Color(0xffbb9af7)),
  'operator': TextStyle(color: Color(0xffbb9af7)),
  'punctuation': TextStyle(color: Color(0xffc0caf5)),
  'root':
      TextStyle(backgroundColor: Color(0xff1a1b26), color: Color(0xff9aa5ce)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.w700),
};
