// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const vs2015Theme = {
  'root':
      TextStyle(backgroundColor: Color(0xff1e1e1e), color: Color(0xffdcdcdc)),
  'keyword': TextStyle(color: Color(0xff569cd6)),
  'literal': TextStyle(color: Color(0xff569cd6)),
  'name': TextStyle(color: Color(0xff569cd6)),
  'symbol': TextStyle(color: Color(0xff569cd6)),
  'link': TextStyle(color: Color(0xff569cd6)),
  'built_in': TextStyle(color: Color(0xff4ec9b0)),
  'type': TextStyle(color: Color(0xff4ec9b0)),
  'class': TextStyle(color: Color(0xffb8d7a3)),
  'number': TextStyle(color: Color(0xffb8d7a3)),
  'string': TextStyle(color: Color(0xffd69d85)),
  'regexp': TextStyle(color: Color(0xff9a5334)),
  'template-tag': TextStyle(color: Color(0xff9a5334)),
  'formula': TextStyle(color: Color(0xffdcdcdc)),
  'function': TextStyle(color: Color(0xffdcdcdc)),
  'params': TextStyle(color: Color(0xffdcdcdc)),
  'subst': TextStyle(color: Color(0xffdcdcdc)),
  'title': TextStyle(color: Color(0xffdcdcdc)),
  'comment': TextStyle(color: Color(0xff57a64a), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff57a64a), fontStyle: FontStyle.italic),
  'doctag': TextStyle(color: Color(0xff608b4e)),
  'meta': TextStyle(color: Color(0xff9b9b9b)),
  'tag': TextStyle(color: Color(0xff9b9b9b)),
  'template-variable': TextStyle(color: Color(0xffbd63c5)),
  'variable': TextStyle(color: Color(0xffbd63c5)),
  'attr': TextStyle(color: Color(0xff9cdcfe)),
  'attribute': TextStyle(color: Color(0xff9cdcfe)),
  'section': TextStyle(color: Color(0xffffd700)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.w700),
  'bullet': TextStyle(color: Color(0xffd7ba7d)),
  'selector-attr': TextStyle(color: Color(0xffd7ba7d)),
  'selector-class': TextStyle(color: Color(0xffd7ba7d)),
  'selector-id': TextStyle(color: Color(0xffd7ba7d)),
  'selector-pseudo': TextStyle(color: Color(0xffd7ba7d)),
  'selector-tag': TextStyle(color: Color(0xffd7ba7d)),
  'addition': TextStyle(backgroundColor: Color(0xff144212)),
  'deletion': TextStyle(backgroundColor: Color(0xff660000)),
};
