// GENERATED CODE - DO NOT MODIFY BY HAND

import 'themes/a11y-dark.dart';
import 'themes/a11y-light.dart';
import 'themes/agate.dart';
import 'themes/an-old-hope.dart';
import 'themes/androidstudio.dart';
import 'themes/arduino-light.dart';
import 'themes/arta.dart';
import 'themes/ascetic.dart';
import 'themes/atom-one-dark-reasonable.dart';
import 'themes/atom-one-dark.dart';
import 'themes/atom-one-light.dart';
import 'themes/brown-paper.dart';
import 'themes/codepen-embed.dart';
import 'themes/color-brewer.dart';
import 'themes/dark.dart';
import 'themes/default.dart';
import 'themes/devibeans.dart';
import 'themes/docco.dart';
import 'themes/far.dart';
import 'themes/felipec.dart';
import 'themes/foundation.dart';
import 'themes/github-dark-dimmed.dart';
import 'themes/github-dark.dart';
import 'themes/github.dart';
import 'themes/gml.dart';
import 'themes/googlecode.dart';
import 'themes/gradient-dark.dart';
import 'themes/gradient-light.dart';
import 'themes/grayscale.dart';
import 'themes/hybrid.dart';
import 'themes/idea.dart';
import 'themes/intellij-light.dart';
import 'themes/ir-black.dart';
import 'themes/isbl-editor-dark.dart';
import 'themes/isbl-editor-light.dart';
import 'themes/kimbie-dark.dart';
import 'themes/kimbie-light.dart';
import 'themes/lightfair.dart';
import 'themes/lioshi.dart';
import 'themes/magula.dart';
import 'themes/mono-blue.dart';
import 'themes/monokai-sublime.dart';
import 'themes/monokai.dart';
import 'themes/night-owl.dart';
import 'themes/nnfx-dark.dart';
import 'themes/nnfx-light.dart';
import 'themes/nord.dart';
import 'themes/obsidian.dart';
import 'themes/panda-syntax-dark.dart';
import 'themes/panda-syntax-light.dart';
import 'themes/paraiso-dark.dart';
import 'themes/paraiso-light.dart';
import 'themes/pojoaque.dart';
import 'themes/purebasic.dart';
import 'themes/qtcreator-dark.dart';
import 'themes/qtcreator-light.dart';
import 'themes/rainbow.dart';
import 'themes/routeros.dart';
import 'themes/school-book.dart';
import 'themes/shades-of-purple.dart';
import 'themes/srcery.dart';
import 'themes/stackoverflow-dark.dart';
import 'themes/stackoverflow-light.dart';
import 'themes/sunburst.dart';
import 'themes/tokyo-night-dark.dart';
import 'themes/tokyo-night-light.dart';
import 'themes/tomorrow-night-blue.dart';
import 'themes/tomorrow-night-bright.dart';
import 'themes/vs.dart';
import 'themes/vs2015.dart';
import 'themes/xcode.dart';
import 'themes/xt256.dart';

const themeMap = {
  'a11y-dark': a11yDarkTheme,
  'a11y-light': a11yLightTheme,
  'agate': agateTheme,
  'an-old-hope': anOldHopeTheme,
  'androidstudio': androidstudioTheme,
  'arduino-light': arduinoLightTheme,
  'arta': artaTheme,
  'ascetic': asceticTheme,
  'atom-one-dark-reasonable': atomOneDarkReasonableTheme,
  'atom-one-dark': atomOneDarkTheme,
  'atom-one-light': atomOneLightTheme,
  'brown-paper': brownPaperTheme,
  'codepen-embed': codepenEmbedTheme,
  'color-brewer': colorBrewerTheme,
  'dark': darkTheme,
  'default': defaultTheme,
  'devibeans': devibeansTheme,
  'docco': doccoTheme,
  'far': farTheme,
  'felipec': felipecTheme,
  'foundation': foundationTheme,
  'github-dark-dimmed': githubDarkDimmedTheme,
  'github-dark': githubDarkTheme,
  'github': githubTheme,
  'gml': gmlTheme,
  'googlecode': googlecodeTheme,
  'gradient-dark': gradientDarkTheme,
  'gradient-light': gradientLightTheme,
  'grayscale': grayscaleTheme,
  'hybrid': hybridTheme,
  'idea': ideaTheme,
  'intellij-light': intellijLightTheme,
  'ir-black': irBlackTheme,
  'isbl-editor-dark': isblEditorDarkTheme,
  'isbl-editor-light': isblEditorLightTheme,
  'kimbie-dark': kimbieDarkTheme,
  'kimbie-light': kimbieLightTheme,
  'lightfair': lightfairTheme,
  'lioshi': lioshiTheme,
  'magula': magulaTheme,
  'mono-blue': monoBlueTheme,
  'monokai-sublime': monokaiSublimeTheme,
  'monokai': monokaiTheme,
  'night-owl': nightOwlTheme,
  'nnfx-dark': nnfxDarkTheme,
  'nnfx-light': nnfxLightTheme,
  'nord': nordTheme,
  'obsidian': obsidianTheme,
  'panda-syntax-dark': pandaSyntaxDarkTheme,
  'panda-syntax-light': pandaSyntaxLightTheme,
  'paraiso-dark': paraisoDarkTheme,
  'paraiso-light': paraisoLightTheme,
  'pojoaque': pojoaqueTheme,
  'purebasic': purebasicTheme,
  'qtcreator-dark': qtcreatorDarkTheme,
  'qtcreator-light': qtcreatorLightTheme,
  'rainbow': rainbowTheme,
  'routeros': routerosTheme,
  'school-book': schoolBookTheme,
  'shades-of-purple': shadesOfPurpleTheme,
  'srcery': srceryTheme,
  'stackoverflow-dark': stackoverflowDarkTheme,
  'stackoverflow-light': stackoverflowLightTheme,
  'sunburst': sunburstTheme,
  'tokyo-night-dark': tokyoNightDarkTheme,
  'tokyo-night-light': tokyoNightLightTheme,
  'tomorrow-night-blue': tomorrowNightBlueTheme,
  'tomorrow-night-bright': tomorrowNightBrightTheme,
  'vs': vsTheme,
  'vs2015': vs2015Theme,
  'xcode': xcodeTheme,
  'xt256': xt256Theme,
};
